branch-defaults:
  master:
    environment: grublr-test
global:
  application_name: grublr
  default_ec2_keyname: keyPair
  default_platform: 64bit Amazon Linux 2015.03 v2.0.0 running Tomcat 8 Java 8
  default_region: us-east-1
  profile: eb-cli
  sc: git
deploy:
  artifact: /home/adi/Projects/GrublrAWS/out/artifacts/grublr/grublr.war